### PR TITLE
Fix severity issue

### PR DESCRIPTION
**Pull request by dorneanu**
Hi! In several tests I have done with your exporter (thanks for sharing, BTW!) I've observed that the `severity` field is not filled in properly. You also have mentioned [in the code](https://github.com/iakovmarkov/prometheus-vuls-exporter/blob/master/src/metrics/parseReport.go#L54) that some changes might be needed. 

In my PR I check for the same field `cvss2Severity` but at different locations. You might also check [tidwall/gjson#268](https://github.com/tidwall/gjson/issues/268) for the solution (it was related to `gjson`, yes). 

I've also added support for Go modules by adding `go.mod` and `go.sum` in the `src/` folder. Now you'll have to `cd src/` and run `go build ...` in order to build the binary. 

I will also add a new PR for building a Docker image. 

Thanks for your time.

Greetings from Berlin, 
Victor

### CODE REVIEW

**Comment by iakovmarkov** [comment]
Hello Victor! Thanks for your contribution, I really appreciate it.
The changes look good to me. Can you please let me know which version of Vuls are you using? I'd like to upgrade my setup and test it to make sure that everything works as expected.

**Comment by dorneanu** [comment]
> Can you please let me know which version of Vuls are you using?
I usually build `vuls` using Docker. This is the current build I have: 

```
─➤  docker run -it vuls/vuls -v      
vuls--build-20220219_002138_
```

And this is my Dockerfile (with small changes: Add non-root user to run vuls):

```
FROM vuls/vuls
RUN addgroup --gid 1000 vuls
RUN adduser --disabled-password --gecos '' --uid 1000 -G vuls vuls
USER vuls
ENTRYPOINT ["vuls"]
CMD ["--help"]
```

**Comment by iakovmarkov** [comment]
Hello @dorneanu. 
I've upgraded my local Vuls setup and tested out your changes. Everything worked as expected!
I am going to build and publish a new release now.
Thanks again for the contribution 🖤

**Comment by dorneanu** [comment]
Hi @iakovmarkov,

thanks for taking care and sharing this exporter at all. Have a nice day!

Greets

**Comment by zhsc** [comment]
Hi @iakovmarkov I'm not seeing the last release after this change.  I'll try and build the code myself, but if it's not too hard for you do you mind pushing a release for others?

Thanks!

**Comment by iakovmarkov** [comment]
Hi @zhsc! I have created new release now: https://github.com/iakovmarkov/prometheus-vuls-exporter/releases

**Comment by zhsc** [comment]
Thank you so much for the quick turnaround!

**Pull request merged**
